### ISSUE TITLE
Cannot clone on Windows

### ISSUE THREAD

**Issue by msink** [LouisCAD/Splitties#156]
```
fatal: cannot create directory at 'gradle_templates/Splitties Android library module/src/androidTest/kotlin/|template|package name': Invalid argument
```

**Comment by LouisCAD** [comment]
Oh no… why, Microsoft… Can you check if it is possible to clone it using Windows subsystem for Linux, and if there's further issues if it is possible?

**Comment by msink** [comment]
Well, I'm currently on Windows7, so no WSL here.
Did it in CYGWIN console.

**Comment by LouisCAD** [comment]
Can you confirm cloning the project now works?

**Comment by msink** [comment]
Thanks, now both `git clone` and `gradlew assemble` passed, `gradlew build` failed on `test_lifecycle_default_scope_uses_default_job`.

**Comment by LouisCAD** [comment]
Oh, sorry, it was not included in the email… I'll take a look in about a week, unless it's a bit urgent to you (let me know, I can take some time even though I'm on vacation). Can you check in the meantime if running the test manually from Android Studio 3.3 RC3 still produces the same error, consistently?

**Comment by msink** [comment]
Not urgent at all. Will try in AS tomorrow.

**Comment by LouisCAD** [comment]
I think opening the project works, and importing fails with kts gradle
files on Android Studio. Can you try by opening the non imported project?

**Comment by msink** [comment]
> Can you try by opening the non imported project?

How? I do not see `.idea` folder on GitHub.

**Comment by LouisCAD** [comment]
No need for it. Just open the project by selecting the directory it's in.

**Comment by msink** [comment]
Well, sorry - that way it opened (didn know, last time tried years ago - it didn't work) 
Had to comment out in publish.gradle
```
        //user = bintray_user
        //key = bintray_api_key
```

So now in AS: it still always fails, but differently: sometimes hangs, sometimes:
```
java.lang.AssertionError: 
Expected :5
Actual   :2
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:48)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:47)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at splitties.lifecycle.coroutines.LifecycleTest$test_scope_is_not_active_after_destroy$1.invokeSuspend(LifecycleTest.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at splitties.lifecycle.coroutines.LifecycleTest.test_scope_is_not_active_after_destroy(LifecycleTest.kt:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code -1
```

**Comment by LouisCAD** [comment]
I'll try to fix the unresolved properties by detecting when they're not there, and will investigate the test issue in several days. Thanks for the feedback, I'll keep you updated.

**Comment by msink** [comment]
Again:
```
git pull
remote: Enumerating objects: 908, done.
remote: Counting objects: 100% (908/908), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 3391 (delta 791), reused 867 (delta 769), pack-reused 2483
Receiving objects: 100% (3391/3391), 426.08 KiB | 636.00 KiB/s, done.
Resolving deltas: 100% (1702/1702), completed with 162 local objects.
From https://github.com/LouisCAD/Splitties
   61a4035b..1d1c1db9  master           -> origin/master
   cc5efdfc..0318f604  develop          -> origin/develop
 * [new branch]        objc-interop-kvo -> origin/objc-interop-kvo
 * [new tag]           v3.0.0-alpha05   -> v3.0.0-alpha05
 * [new tag]           v3.0.0-alpha06   -> v3.0.0-alpha06
fatal: cannot create directory at 'scripts/gradle_templates/Splitties Multiplatform library module (targets:android)': Invalid argument
```
":" is forbidden in filenames.

**Comment by LouisCAD** [comment]
What would you replace it with?

**Comment by msink** [comment]
'=' works for me.

**Comment by LouisCAD** [comment]
Added a little of Kotlin syntax in the directory names for the fun.
Fixed on branches `master`, `develop` and `objc-interop-kvo`.

Thanks for the report!
