### ISSUE TITLE
IDE preview not working

### ISSUE THREAD

**Issue by christopheblin** [LouisCAD/Splitties#210]
I'm trying to use the Views DSL IDE preview like this :

res/layout/debug.xml

```
<?xml version="1.0" encoding="utf-8"?>
<splitties.views.dsl.idepreview.UiPreView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:splitties_class_fully_qualified_name="com.myapplication.TmpUi"/>
```

com/myapplication/Tmp.kt
```
class TmpUi(override val ctx: Context) : Ui {
    override val root = verticalLayout {
        add(textView {
            text = "TMP"
        }, lParams(wrapContent, wrapContent))
    }
}
```

Then I have nothing visible in the preview and the following error :

```
java.lang.NoClassDefFoundError: splitties/views/dsl/idepreview/R$styleable
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:49)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:43)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

Any idea what I am doing wrong ?

I am using
Android Studio 3.5

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.louiscad.splitties:splitties-fun-pack-android-material-components-with-views-dsl:3.0.0-alpha06'
    implementation("com.louiscad.splitties:splitties-views-dsl-ide-preview:3.0.0-alpha06")
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by LouisCAD** [comment]
Hi, run the `mergeDebugJavaResource` Gradle task on the target module (see
the Gradle pane) and your issue should be fixed.

Can you confirm it works now?

**Comment by christopheblin** [comment]
yes it works, thanks

**Comment by LouisCAD** [comment]
Note that the IDE Preview should be using the `debugImplementation` configuration, not `implementation`.

Also, FYI, this artifact will be deprecated in next version as the Views DSL version will directly bundle IDE Preview in its debug version (package name and all won't change, don't worry), making configuration easie.
