### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by vitaviva** [LouisCAD/Splitties#232]
Hi，

when try previewing with preview_demo_ui.xml, following exception happens：
（AndroidStudio 3.5.3）

```
java.lang.ClassNotFoundException: com.louiscad.splittiessample.demo.DemoUi
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:201)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:61)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:135)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:235)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:60)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:43)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:323)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:394)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:200)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:572)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:698)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I have run a full build，and how should I do to make preview working?

**Comment by LouisCAD** [comment]
You said you ran a full build. Did you try to refresh the layout preview afterwards?

If not, please, can you tell me which Splitties version your are using, and which Android Studio version as well?

**Comment by vitaviva** [comment]
> You said you ran a full build. Did you try to refresh the layout preview afterwards?
> 
Yes，I did

> If not, please, can you tell me which Splitties version your are using, and which Android Studio version as well?

ran with the source (commit: 0ec1a317669876147ac39365f41be5f8b67c2e3e),
Android Studio：3.5.3

**Comment by vitaviva** [comment]
after branch changed to develop , problem is solved，close
