### ISSUE TITLE
Preview not working when UI class is an inner class

### ISSUE THREAD

**Issue by gtf35** [LouisCAD/Splitties#246]
HI,I like to write `Ui`  code in  Activity's inner classes (in MVVM, Activity class is V), but preview is not working

like this:

```
package top.gtf35.frontbackgroundcheck

class MainActivity : AppCompatActivity() {
    private val ui by lazy { MainUI(this) }
    private val rootView by lazy { ui.root }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(rootView)
    }

    inner class MainUI(override val ctx: Context) : Ui {
        override val root: View
            get() = xxx
    }
}
```

Preview xml code is:

```
<?xml version="1.0" encoding="utf-8"?>
<splitties.views.dsl.idepreview.UiPreView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:splitties_class_package_name_relative="MainActivity.MainUI"/>
```

And error log is:

```
java.lang.ClassNotFoundException: top.gtf35.frontbackgroundcheck.MainActivity.MainUI
	at com.android.tools.idea.rendering.classloading.RenderClassLoader.loadClassFromNonProjectDependency(RenderClassLoader.java:123)
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:153)
	at com.android.tools.idea.rendering.classloading.RenderClassLoader.findClass(RenderClassLoader.java:78)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:187)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:60)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt:43)
	at splitties.views.dsl.idepreview.UiPreView.<init>(UiPreView.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:416)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:427)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:331)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:501)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:348)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:404)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:678)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$8(RenderTask.java:809)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

That is all, thank you very much :)

**Comment by LouisCAD** [comment]
Hi, it's not supported so just remove the `inner` keyword and voilà.

BTW, you're not implementing `Ui` properly, you need to use replace the getter for `root` with an assignment, as shown in documentation and sample, or you'll get hard to diagnose errors as multiple view hierarchies will be created.

**Comment by gtf35** [comment]
Thank you for your reply.
But when I remove `inner` , still can't preview, and the error log is the same as before.

And you are right, I should not use getter(this is why I previously defined a constant to save ```Ui```‘s root View),

Thanks again

**Comment by LouisCAD** [comment]
You need to replace the dot separating the host class name from the target class name with a dollar sign.

Note that I'll make changes soon that will allow to preview without xml on Android Studio 4.1+ (and 4.0 too maybe, I didn't check), and you'll use an actual reference to the class that will be compiled, avoiding such issues.

**Comment by gtf35** [comment]
wow, success 🤣🤣
Thanks a lot.

The new feature sounds cool.
