### ISSUE TITLE
Weird NoClassDefFoundError: kotlin.collections.EmptyList under api 21

### ISSUE THREAD

**Issue by RavioliWonton** [LouisCAD/Splitties#278]
After upgraded to Kotlin 1.5.21, I came into this error with com.louiscad.splitties:splitties-appctx:3.0.0-beta02: 

> E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoClassDefFoundError: kotlin.collections.EmptyList
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: androidx.startup.StartupException: java.lang.NoClassDefFoundError: kotlin.collections.EmptyList
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1058)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4560)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: kotlin.collections.EmptyList
        at kotlin.collections.CollectionsKt__CollectionsKt.emptyList(Collections.kt:71)
        at splitties.init.AppCtxInitializer.dependencies(AppCtxInitializer.kt:30)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:143)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1058) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:4560) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by RavioliWonton** [comment]
I believe there is something weird about multidex with kotlin. It's not work by configuring multiDexKeepFile. I will keep tracking this issue and close this for it's not Splitties's fault.

**Comment by RavioliWonton** [comment]
I understand what happened.
Since migrating to androidx.startup, I cannot use appCtx in Application's static code block or companion object in kotlin(which is initialized through Application's construction, this instance is not accessible refer to [document](https://github.com/LouisCAD/Splitties/blob/9a4194b35ce9d79d31816b3d4df729863219f4e3/modules/appctx/src/androidMain/kotlin/splitties/init/AppCtx.kt#L22)), there is a reproduce [project](https://drive.google.com/file/d/1abixnSMyQEzG2yY0h1e5ChFpLx5qAneV/view?usp=sharing).
If this should be an intended behaviour, please close this, or I can issue a bug report to google. Reopen the issue.

**Comment by LouisCAD** [comment]
You can workaround by calling `context?.injectAsAppCtx()` early in an `init` block in your `Application` class.

**Comment by RavioliWonton** [comment]
> context?.injectAsAppCtx()

Thanks for the reply, but it's not work in initialization of Application class. Inject into applicationContext will get NullPointerException, and inject into baseContext will get the same error of NoClassDefFoundError.

**Comment by LouisCAD** [comment]
Can you make a small reproducing project?

**Comment by RavioliWonton** [comment]
> Can you make a small reproducing project?

Sure, it's [here](https://drive.google.com/file/d/1abixnSMyQEzG2yY0h1e5ChFpLx5qAneV/view?usp=sharing).

**Comment by LouisCAD** [comment]
The project you shared doesn't reproduce the bug it seems. The app doesn't crash on launch, and I see no relevant logs.

**Comment by RavioliWonton** [comment]
> The project you shared doesn't reproduce the bug it seems. The app doesn't crash on launch, and I see no relevant logs.

I'm sorry I forget to mention that this situation will only appear on devices under api 21, which need MultiDex to move past 65K limitation.

**Comment by LouisCAD** [comment]
Hello, can you try to use AndroidX App Startup 1.1.0-rc01?

See the related changelog here: https://developer.android.com/jetpack/androidx/releases/startup#1.1.0-rc01

**Comment by LouisCAD** [comment]
Should be fixed in 3.0.0-rc01 via AndroidX App Startup upgrade.

**Comment by RavioliWonton** [comment]
It fixed my problem, thank you!
