### ISSUE TITLE
update the version of "constraintlayout"

### ISSUE THREAD

**Issue by autught** [LouisCAD/Splitties#307]
some problem may happen when using current version
in my case ,"constraintlayout" is used as the contentView of activity,when remove a child of the contentView and add this to the decorView of activity ,then set the activity orientation SCREEN_ORIENTATION_LANDSCAPE, a problem of "**android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams**" happens.
the issue of "https://github.com/luckybilly/Gloading/issues/13" inspire me, i update the version of "**2.1.4**" so that the problem has been solved

**Comment by autught** [comment]
<html>
<body>

12-27 10:33:10.425 18048 18048 E AndroidRuntime: java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams
--
5012-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:749)
5112-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:426)
5212-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:335)
5312-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:117)
5412-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1532)
5512-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1607)
5612-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
5712-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
5812-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
5912-27 10:33:10.425 18048 18048 E AndroidRuntime: at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
6012-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
6112-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
6212-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
6312-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
6412-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
6512-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
6612-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
6712-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
6812-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
6912-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
7012-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
7112-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
7212-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
7312-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
7412-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
7512-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
7612-27 10:33:10.425 18048 18048 E AndroidRuntime: at com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
7712-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.View.measure(View.java:24856)
7812-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3119)
7912-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1931)
8012-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
8112-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
8212-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
8312-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
8412-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:865)
8512-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:800)
8612-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
8712-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
8812-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
8912-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.os.Looper.loop(Looper.java:224)
9012-27 10:33:10.425 18048 18048 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7562)
9112-27 10:33:10.425 18048 18048 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
9212-27 10:33:10.425 18048 18048 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
9312-27 10:33:10.425 18048 18048 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


</body>
</html>
